theme: jekyll-theme-cayman


description: learn by writing and sharing

safe: true
lsi: false
pygments: true
simple_search: http://google.com/search
markdown: kramdown
paginate: 10
kramdown:
  extensions:
    - autolink
    - footnotes
    - smart
permalink: /:year/:month/:title.html
relative_permalinks: false
url: https://221bc.github.io/
#url: http://localhost:2106
#port: 2106
#baseurl: /project-name
name: abchin
timezone:    Aisa/Beijing
# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
title : abchin
tagline: love Github repositories
author :
  name : abchin
  email : tigefa@gmail.com
  tumblr: tigefa
  flickr: tigefa
  github : tigefa4u
  repository: tigefa4u.github.io
  gittip: tigefa
  twitter : tigefa_team
  facebook: tigefa.team
  feedburner : tigefa4ugithub
  linkedin: tigefadotinfo
  googleplus: tigefa
  pinterest: tigefa
  bitbucket: tigefa4u
  stackoverflow: tigefa
