theme: jekyll-theme-cayman

description: learn by writing and sharing

safe: true
lsi: false
pygments: true
simple_search: http://google.com/search
paginate: 10
markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:title.html
relative_permalinks: false
url: https://guoyang.github.io/
#url: http://localhost:2106
#port: 2106
#baseurl: /project-name
name: SaltyLux
timezone: Asia/Beijing
# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
title: SaltyLux
author: SaltyLux
name: SaltyLux
